Use LDLIBS

+++ src/build/Makefile	2023-07-08 00:17:35.216448236 +0200
@@ -74,9 +74,9 @@
 
 OBJS = $(SRCS:.c=.o)
 
-LIBS = -lm
+#LIBS = -lm
 
-CPPFLAGS = -I. -I$(srcdir)
+override CPPFLAGS += -I. -I$(srcdir)
 
 $(OBJS): Parser.h
 
@@ -89,7 +89,7 @@
 	flex -Pasm -Cem -8 -o $@ $<
 
 $(TARGETNAME): $(OBJS) 
-	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(LDLIBS) -o $@ $(OBJS) $(LIBS)
 
 
 
