+++ src/makefile	2023-07-05 16:26:01.853251699 +0200
@@ -13,15 +13,16 @@
 # Required modules (uses pkg-config)
 PKGS = sdl SDL_image x11
 
-CXXFLAGS += $(shell pkg-config --cflags $(PKGS))
-LIBS += $(shell pkg-config --libs $(PKGS))
+#CXXFLAGS += $(shell pkg-config --cflags $(PKGS))
+#LIBS += $(shell pkg-config --libs $(PKGS))
 
 # No pkg-config module for SDL_ttf and zlib (on some systems)
 LIBS += -lSDL_ttf -lz
 
+override CXXFLAGS += -IBox2D/Include -I. -DGENODE \
+         -DINSTALL_BASE_PATH='"/"' -DUSER_BASE_PATH='"/"'
 
 # Box2D Library
-CXXFLAGS += -IBox2D/Include
 BOX2D_SOURCE := Box2D/Source
 BOX2D_LIBRARY := Gen/float/libbox2d.a
 LIBS += $(BOX2D_SOURCE)/$(BOX2D_LIBRARY)
@@ -47,7 +48,7 @@
 	xxd -i $< $@
 
 $(APP): $(OBJECTS) $(BOX2D_SOURCE)/$(BOX2D_LIBRARY)
-	$(CXX) -o $@ $^ $(LIBS)
+	$(CXX) -o $@ $^ $(LDLIBS) $(LDFLAGS)
 
 
 clean:
